version: "3.7"

services:
   nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - "./nginx/config:/etc/nginx/conf.d"
      ports:
        - "80:80"
        - "443:443"
      networks:
        - server
#  - sonar:

networks:
  server:
    name: server
    external: false